services:
  - type: web
    name: prysm-clean
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        sync: false
