"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createSupabaseBrowser} from "../../../lib/supabase-browser";
type P={id:string;username:string;display_name:string;avatar_url:string|null;age:number|null;location:string|null};
export default function FavorisPage(){const supabase=createSupabaseBrowser();const [profiles,setProfiles]=useState<P[]>([]);const [loading,setLoading]=useState(true);
useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return;}const {data:f}=await supabase.from("dating_favorites").select("favorite_id").eq("user_id",user.id).order("created_at",{ascending:false});const ids=(f??[]).map(x=>x.favorite_id);if(ids.length){const {data:p}=await supabase.from("profiles").select("id,username,display_name,avatar_url,age,location").in("id",ids);setProfiles((p??[]) as P[])}setLoading(false)}void load()},[]);
return <main className="shell"><header className="topbar"><Link className="brand" href="/">PRYSM</Link><nav><Link href="/">Accueil</Link><Link href="/forum">Forum</Link><Link className="active" href="/rencontres">Rencontres</Link><Link href="/profil">Profil</Link></nav></header><section className="page-head"><p className="eyebrow">Rencontres</p><h1>Mes favoris.</h1><p className="lead">Les profils que tu veux retrouver facilement.</p><div className="actions"><Link className="button" href="/rencontres">Découvrir les profils</Link></div></section>{loading?<div className="empty"><p>Chargement…</p></div>:!profiles.length?<div className="empty"><div className="empty-symbol">☆</div><h2>Aucun favori</h2><p>Ajoute un profil à tes favoris depuis sa fiche.</p></div>:<section className="cards">{profiles.map(p=><Link className="card" href={"/membre/"+p.username} key={p.id}><div className="avatar">{p.avatar_url?<img src={p.avatar_url} alt=""/>:(p.display_name||p.username).slice(0,1).toUpperCase()}</div><span>@{p.username}</span><h3>{p.display_name||p.username}{p.age!==null?", "+p.age:""}</h3>{p.location&&<p>{p.location}</p>}<strong>★ Favori →</strong></Link>)}</section>}</main>
}
