"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { createSupabaseBrowser } from "../../../../lib/supabase-browser";
import MentionInput from "../../../components/mention-input";
function friendlyError(message:string){if(message.includes("ANTI_SPAM_DUPLICATE"))return "Ce sujet ressemble trop à une publication récente. Modifie le titre ou le message avant de réessayer.";if(message.includes("RATE_LIMIT_EXCEEDED")||message.includes("rate limit")||message.includes("check_rate_limit"))return "Tu publies trop rapidement. Attends un peu avant de créer un nouveau sujet.";return message;}
export default function NewTopic(){const {slug}=useParams<{slug:string}>();const supabase=createSupabaseBrowser();const [categoryId,setCategoryId]=useState("");const [title,setTitle]=useState("");const [body,setBody]=useState("");const [pollQuestion,setPollQuestion]=useState("");const [pollOptions,setPollOptions]=useState(["",""]);const [multiplePoll,setMultiplePoll]=useState(false);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
useEffect(()=>{supabase.from("forum_categories").select("id").eq("slug",slug).maybeSingle().then(({data})=>setCategoryId(data?.id||""));},[slug]);
async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return;}if(!categoryId){setError("Section introuvable.");setLoading(false);return;}
const {data,error}=await supabase.rpc("create_topic_with_first_post",{p_category_id:categoryId,p_title:title,p_body:body});if(error||!data){setError(friendlyError(error?.message||"Impossible de créer le sujet."));setLoading(false);return;}
const topicId=data as string;const cleanOptions=pollOptions.map(x=>x.trim()).filter(Boolean);
if(pollQuestion.trim()||cleanOptions.some(Boolean)){if(pollQuestion.trim().length<3||cleanOptions.length<2){setError("Un sondage doit avoir une question et au moins deux choix.");setLoading(false);return;}const pollResult=await supabase.rpc("create_poll_for_topic",{p_topic_id:topicId,p_question:pollQuestion.trim(),p_options:cleanOptions,p_multiple_choice:multiplePoll});if(pollResult.error){setError(pollResult.error.message);setLoading(false);return;}}
window.location.href="/topic/"+topicId;}
return <main className="shell"><header className="topbar"><Link className="brand" href="/">PRYSM</Link><nav><Link href="/forum">Forum</Link><Link href="/profil">Profil</Link></nav></header><section className="page-head compact"><Link className="back" href={"/forum/"+slug}>← Retour à la section</Link><p className="eyebrow">Nouvelle discussion</p><h1>Ouvrir un sujet.</h1></section><form className="auth-card topic-form" onSubmit={submit}><label>Titre<input required minLength={3} maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Message<MentionInput required maxLength={10000} placeholder="Ton message… Utilise @pseudo pour mentionner quelqu’un." value={body} onChange={setBody}/></label>
<fieldset className="poll-builder"><legend>📊 Ajouter un sondage <span>optionnel</span></legend><label>Question<input maxLength={500} placeholder="Quelle option préfères-tu ?" value={pollQuestion} onChange={e=>setPollQuestion(e.target.value)} /></label>{pollOptions.map((option,i)=><label key={i}>Choix {i+1}<input maxLength={180} value={option} onChange={e=>setPollOptions(current=>current.map((x,j)=>j===i?e.target.value:x))} /></label>)}{pollOptions.length<8&&<button type="button" className="button ghost" onClick={()=>setPollOptions(current=>[...current,""])}>+ Ajouter un choix</button>}<label className="checkbox-row"><input type="checkbox" checked={multiplePoll} onChange={e=>setMultiplePoll(e.target.checked)} /> Autoriser plusieurs choix</label></fieldset>
{error&&<div className="notice error">{error}</div>}<button className="button primary" disabled={loading}>{loading?"Publication…":"Publier le sujet"}</button></form></main>}
